export type BoardMember = {
  name: string
  title: string
  bio: string
  fullBio: string
  image: string | null
}

export const boardMembers: BoardMember[] = [
  {
    name: "Cynthia Darko Acquaye",
    title: "Board Chair",
    bio: "Cynthia is a seasoned leader in both real estate and energy sectors, boasting over 25 years of experience within the CH Group's diverse subsidiaries. Currently, she serves as the COO of the CH Group and holds a board position in Goldkey Properties, the largest asset owner of real estate in the country, Tema Tank Farm- largest privately owned petroleum storage depot in Ghana, Base Energy, operators of the ESWT block, Chase Petroleum Ghana Limited- a leading bulk distribution company and Veolia Ghana- an environmental services and solutions provider.",
    fullBio:
      "Cynthia is a seasoned leader in both real estate and energy sectors, boasting over 25 years of experience within the CH Group's diverse subsidiaries. Currently, she serves as the COO of the CH Group and holds a board position in Goldkey Properties, the largest asset owner of real estate in the country, Tema Tank Farm- largest privately owned petroleum storage depot in Ghana, Base Energy, operators of the ESWT block, Chase Petroleum Ghana Limited- a leading bulk distribution company and Veolia Ghana- an environmental services and solutions provider.\n\nIn her role as Group COO, Cynthia's focus is on steering strategic direction and pursuing growth opportunities across the Group's various entities. Cynthia's career has spanned over two decades, initially transitioning into real estate in 2003 from petroleum trading to spearhead the development and expansion of Goldkey Properties within the CH Group. Over the years, she has grown the business from a startup with an $18,000 annual rental income to a remarkable $100 million asset portfolio.\n\nHer expertise encompasses the full spectrum of real estate, including land acquisition, investment analysis, project management, construction, property sales and leasing, as well as strategic planning. Throughout her tenure, Cynthia's leadership has significantly evolved Goldkey Properties, driving its transition from purely residential holdings to include commercial and mixed-use projects, exemplified by the award-winning Cantonments City development. She has also played significant roles in the development of the businesses in the oil and gas sector. She has a vast experience in Petroleum upstream, mid and downstream industry. She is also known for her dedication to social responsibility, actively contributing to charitable initiatives and community development.\n\nHer educational background includes Commercial Real Estate Analysis and Investment studies from MIT, an MBA in International Business from Birmingham Business School, and leadership training from Harvard Business School. Cynthia's accomplishments and multiple awards received stand as a testament to her extensive experience in project development, strategy formulation, and cross functional leadership, making her a driving force behind CH Group's diverse and thriving businesses.",
    image: "/board_and_management/cynthia_darko_acquaye.png",
  },
  {
    name: "Mishael Nii Amu Offei",
    title: "Non Executive Director",
    bio: "Mishael serves as the Chief Business Officer for the CH Group, where he oversees the execution of pivotal business development initiatives across the organization. With a strategic vision and an eye for sustainable growth, Mishael plays a crucial role in steering the Group toward new opportunities and enhancing its market position.",
    fullBio:
      "Mishael serves as the Chief Business Officer for the CH Group, where he oversees the execution of pivotal business development initiatives across the organization. With a strategic vision and an eye for sustainable growth, Mishael plays a crucial role in steering the Group toward new opportunities and enhancing its market position.\n\nMishael brings extensive and diverse experience across West Africa in Corporate Finance Advisory and Strategy, underscoring his reputation as a leader in complex financial and strategic endeavors. His expertise encompasses mergers and acquisitions, capital raising, strategy development and implementation, financial engineering, corporate restructuring, and turnaround management. Throughout his career, Mishael has demonstrated an exceptional ability to navigate intricate financial landscapes and deliver results that drive long-term value.\n\nBefore joining the Group, Mishael held the position of Head of Financial Advisory at Oakwood Green Capital Limited. In this role, he led high-profile financial advisory projects, fostering relationships with key stakeholders and delivering tailored solutions that enhanced client outcomes. Prior to this, he was the Chief Executive Officer of Omega Signature, where he successfully spearheaded strategic initiatives that repositioned the company for growth and operational efficiency.\n\nMishael's educational background further underscores his commitment to excellence. He holds an MSc in Political Economy of Late Development from the prestigious London School of Economics and Political Science, which equipped him with a deep understanding of economic policy and global development challenges. Additionally, he earned a BSc in Business Administration from Ashesi University College, where he cultivated foundational knowledge in business management and leadership.",
    image: "/board_and_management/mishael_nii_amu_offei.png",
  },
  {
    name: "Karen Asafu-Adjaye",
    title: "Non Executive Director",
    bio: "Karen Asafu-Adjaye is a Programme Management Executive with 20 years of international experience leading complex systems implementations, technology transformations, and large-scale project delivery - including over a decade driving initiatives in Ghana's extractive industry.",
    fullBio:
      "Karen Asafu-Adjaye is a Programme Management Executive with 20 years of international experience leading complex systems implementations, technology transformations, and large-scale project delivery - including over a decade driving initiatives in Ghana's extractive industry. She combines strategic leadership with deep project management expertise to deliver transformation and measurable results.\n\nAs Director of Programme Management and IT at the Ghana Integrated Aluminium Development Corporation (GIADEC), Karen leads the execution of Ghana's Integrated Aluminium Industry Master Plan - a national transformation programme designed to fully leverage Ghana's bauxite resources, accelerate industrialisation, and drive sustainable economic growth for the country.\n\nPreviously, Karen served as Business Performance Manager at Tullow Oil, where she implemented and managed the Ghana Business Unit's Performance Management Framework, delivering insightful reporting and analysis that informed key strategic decisions by the leadership team.\n\nEarlier in her career, Karen was a Technology Consultant in the UK, where she delivered major systems transformation programmes for clients across Europe in industries including financial services, media, energy, retail, and government.\n\nKaren holds a degree in Information Systems Engineering from the University of Manchester (UK), an Advanced Management Certificate from China Europe International Business School (CEIBS) and is currently pursuing a Global Executive MBA to further strengthen her strategic leadership and global business expertise.\n\nShe is passionate about using technology and programme delivery to drive innovation and create value.",
    image: "/board_and_management/karen_asafu_adjaye.png",
  },
  {
    name: "Samuel Kwamena Ewusie Arthur",
    title: "Non Executive Director",
    bio: "Samuel Arthur is an investment and advisory professional with over 20 years of experience across Africa and the United States. His career spans commodities credit risk, venture investing, and leadership roles in fintech and digital transformation.",
    fullBio:
      "Samuel Arthur is an investment and advisory professional with over 20 years of experience across Africa and the United States. His career spans commodities credit risk, venture investing, and leadership roles in fintech and digital transformation — all anchored by a consistent focus on scaling businesses and creating long-term value.\n\nHe began his career at Salomon Smith Barney before joining MF Global in New York, where he managed an Energy, Metals, and Agricultural Counterparty Credit Risk portfolio with a market exposure of over US$3.0 billion across the USA, Asia, and South America.\n\nIn 2012, he became Partner and Executive Director at Merson Capital, overseeing the firm's principal investments portfolio in real estate, healthcare, technology, energy infrastructure, and financial services. Since then, he has founded, managed, and invested in ventures across fintech, banking, real estate, human resources, healthcare, and events management.\n\nIn 2020, he transitioned into the technology sector as Country Manager of Vantage Scan Ghana Limited, a pan-African fintech providing white-label payment solutions for banks, telecoms, online marketplaces, and sports betting companies. He currently serves as Vice-Chairman of Sazience Technology, a Dubai-based digital transformation platform operating in 16 countries across the Middle East and Africa.\n\nHe holds an MSc in Finance from George Washington University and a BSc in Business Administration (Finance) from the University of North Carolina at Charlotte.",
    image: null,
  },
  {
    name: "Philip Danquah",
    title: "Non Executive Director",
    bio: "Philip Danquah is an Investment Banker and Chartered Accountant with over 22 years of experience. His expertise spans across private equity investment management, microfinance, banking, accounting, management consulting and taxation.",
    fullBio:
      "Philip Danquah is an Investment Banker and Chartered Accountant with over 22 years of experience. His expertise spans across private equity investment management, microfinance, banking, accounting, management consulting and taxation. Philip has contributed in growing SMEs across Africa.\n\nHe began his career at Value Added Tax (VAT) Service in 2003, where he generated significant tax revenue for the Government of Ghana.\n\nIn 2005, Philip joined the pioneer team that established Guaranty Trust Bank in Ghana. He served as the Head of Banking Operations at the Tema Branch.\n\nIn 2008, he joined Mustard Capital Partners Limited (private equity Investment Advisers) as an Investment Manager, where he managed Fidelity Equity Fund II Limited, a US$23 million SME private equity Fund that invest in SMEs in West Africa. He currently serves as the Chief Investment Officer (CIO) & Chief Finance Officer (CFO) at Mirepa Investment Advisors, a private equity fund management company focusing on investing in SMEs in Ghana.\n\nPhilip served as the Managing Director of Growth Pioneers Microfinance Limited (now Surge Microfinance Limited) from 2014 to 2022. He attended several training programs on microfinance during this period.\n\nPhilip is a Chartered Certified Accountants (ACCA). He holds an Executive MBA in Finance from the University of Ghana Business School and Bachelor of Commerce Degree (B. Com) from the University of Cape Coast. Philip also holds the Chartered Institute of Securities and Investment - UK (CISI) professional qualification. Philip also holds the Ghana Securities & Exchange Commission (SEC) Investment Advisers License.\n\nHe holds an MSc in Finance from George Washington University and a BSc in Business Administration (Finance) from the University of North Carolina at Charlotte.",
    image: "/board_and_management/philip_danquah.jpg",
  },
]

export function memberImageUrl(member: BoardMember) {
  if (member.image) return member.image
  return `https://ui-avatars.com/api/?name=${encodeURIComponent(member.name)}&background=211C41&color=fff&size=600&bold=true`
}
